[package]
name = "dvd-screensaver"
version = "0.1.0"
authors = ["David Thompson <davidethompson@me.com>"]
edition = "2018"

[dependencies]
pancurses = "0.16.1"
ctrlc = { version = "3.1.9", features = ["termination"] }